server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      allowOverride: true
      server:
        native:
          searchLocations: classpath:config/,classpath:config/eureka-service,classpath:config/zuul-service
