eureka:
  instance:
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://eureka-service-api.herokuapp.com/eureka/
#      defaultZone: http://localhost:8761/eureka/
